plugins {
    id 'com.gradleup.shadow' version '9.6.1' apply false
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'com.cleanroommc.conventions'

    group = 'com.cleanroommc'

    conventions {
        repositoryUrl = 'https://github.com/CleanroomMC/Installer'
    }

    java {
        toolchain {
            vendor = JvmVendorSpec.AZUL
        }
    }

    tasks.named('test', Test) {
        javaLauncher = javaToolchains.launcherFor {
            languageVersion = JavaLanguageVersion.of(25)
        }
        systemProperty 'java.awt.headless', 'true'
    }
}
