version = 0.1.0
versioning.stage = beta

org.gradle.welcome = never
org.gradle.warning.mode = all
org.gradle.logging.stacktrace = all
org.gradle.console = verbose
org.gradle.parallel = true
org.gradle.caching = true

java_utils_version = 2.1.6
platform_utils_version = 2.0.0
gson_version = 2.8.9
slf4j_version = 2.0.17
jspecify_version = 1.0.0
junit_version = 5.10.2
